export const HotelTypes = [
  "Budget",
  "Boutique",
  "Luxury",
  "Ski Resort",
  "Business",
  "Family",
  "Romantic",
  "Hiking Resort",
  "Cabin",
  "Beach Resort",
  "Golf Resort",
  "Motel",
  "All Inclusive",
  "Pet Friendly",
  "Self Catering",
];

export const HotelFacilities = [
  "Free Wi-Fi",
  "Car Rental",
  "Room Service",
  "Outdoor Pool",
  "Spa & Sauna",
  "Fitness Room",
  "EV Charging",
  "Kids' Zone",
  "Daily Clean",
  "Mini Fridge",
  "Cafe & Bar",
  "Concierge",
  "24h Front",
  "Wheelchair",
  "Meeting Hub",
];
